database:
  url: jdbc:postgresql://${db.hostname:localhost}:5432/msaportal

spring:
  datasource:
    url: jdbc:postgresql://${db.hostname:localhost}:5432/msaportal
    username: msaportal
    password: msaportal
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
  cloud:
    stream:
      bindings:
        attachmentEntity-out-0: # 첨부파일 entity 정보 업데이트 하기 위한 이벤트
          destination: attachment-entity.topic # queue name
          group: attachment
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: false
        default_batch_fetch_size: 1000
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: postgresql
