database:
  url: jdbc:postgresql://${db.hostname:localhost}:5432/msaportal

spring:
  r2dbc:
    url: r2dbc:postgresql://${db.hostname:localhost}:5432/msaportal
    username: msaportal
    password: msaportal
    pool:
      enabled: true
      initial-size: 10
      max-size: 30
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_batch_fetch_size: 1000
    show-sql: true
  cloud:
    bus:
      destination: springCloudBus
    stream:
      function:
        definition: reserveRequest;busConsumer # 예약 요청후 물품 재고업데이트 이벤트에 대한 consumer function & springcloudbus consumer function
      bindings:
        busConsumer-in-0:
          destination: ${spring.cloud.bus.destination}
        reserveRequest-in-0: # 예약 요청후 물품 재고업데이트 이벤트에 대한 consumer binding
          destination: reserve-request.topic # queue name
          group: reserved
        inventoryUpdated-out-0: # 예약 요청후 물품 재고업데이트 결과에 이벤트에 대한 supplier binding
          destination: inventory-updated.topic # queue name
          group: reserved
