server:
  port: 0 # random port

spring:
  application:
    name: attach-service
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        globally_quoted_identifiers: false
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

# config server actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info

info:
  app:
    name: Attach Service
    description: 첨부파일 관리 기능을 제공
